<?php
return [
    '_LANG_NAME' => 'Deutsch',
    '_LANG_AUTHOR' => 'rGunti',
    '_LANG_BY_STRING' => 'von %1$s',

    'app_version' => 'App Version',

    'copyright_title' => 'Copyright',
    'copyright_content' => 'Copyright &COPY; %1$s rGunti',

    'language' => 'Sprache',
    'languages' => 'Sprachen',

    'login' => 'Login',
    'logout' => 'Logout',
    'save' => 'Speichern',

    'debug_title' => 'Debug Info',
    'debug_no_items' => 'keine Elemente',
    'debug_session_info' => 'Session Info',
    'debug_instance' => 'Instanz',

    'home' => 'Home',

    'username' => 'Benutzername',
    'password' => 'Passwort',
    'mail_address' => 'E-Mail-Adresse',

    'toggle_nav' => 'Navigation anzeigen / ausblenden',

    'user_settings_title' => 'Benutzereinstellungen',
    'change_password' => 'Passwort ändern',
    'confirm_password' => 'Geändertes Passwort bestätigen',
    'change_password_help' => 'Wenn du das Passwort nicht ändern möchtest, lass die Passwortfelder leer.',

    'tos_title' => 'Nutzungsbedingungen',
    'tos_content' => 'Nutzungsbedingungen wurden noch nicht erstellt.',
];
