<?php
return [
    '_LANG_NAME' => 'Deutsch',
    '_LANG_AUTHOR' => 'rGunti',
    '_LANG_BY_STRING' => 'von %1$s',
    '_LANG_FLAG' => '/img/lang/flag-germany.png',

    'app_version' => 'App Version',

    'copyright_title' => 'Copyright',
    'copyright_content' => 'Copyright &COPY; %1$s rGunti',

    'language' => 'Sprache',
    'languages' => 'Sprachen',

    'login' => 'Login',
    'logout' => 'Logout',
    'save' => 'Speichern',

    'debug_title' => 'Debug Info',
    'debug_no_items' => 'keine Elemente',
    'debug_session_info' => 'Session Info',
    'debug_instance' => 'Instanz',

    'home' => 'Home',

    'username' => 'Benutzername',
    'password' => 'Passwort',
    'mail_address' => 'E-Mail-Adresse',

    'toggle_nav' => 'Navigation anzeigen / ausblenden',

    'user_settings_title' => 'Benutzereinstellungen',
    'change_password' => 'Passwort ändern',
    'confirm_password' => 'Geändertes Passwort bestätigen',
    'change_password_help' => 'Wenn du das Passwort nicht ändern möchtest, lass die Passwortfelder leer.',

    'tos_title' => 'Nutzungsbedingungen',
    'tos_content' => 'Nutzungsbedingungen wurden noch nicht erstellt.',

    'message_logged_in' => 'Willkommen, %1$s',
    'message_logged_in_content' => 'Du wurdest erfolgreich angemeldet!',
    'message_logged_out' => 'Du wurdest erfolgreich abgemeldet!',

    'error_login_invalid' => 'Ungültige Login-Daten',
    'error_login_invalid_content' => 'Deine Login-Daten scheinen ungültig zu sein. Bitte überprüfe deine Eingabe und versuche es noch einmal.',

    'error_login_blocked' => 'Gesperrt',
    'error_login_blocked_content' => 'Dein Account wurde gesperrt.',

    'error_navigation_login_needed' => 'Login benötigt',
    'error_navigation_login_needed_content' => 'Bitte melde dich an, um diesen Inhalt sehen zu können.',
];
