<?php
return [
    '_LANG_NAME' => 'English (default)',
    '_LANG_AUTHOR' => 'rGunti',
    '_LANG_BY_STRING' => 'by %1$s',
    '_LANG_FLAG' => '/img/lang/flag-united-kingdom.png',

    'app_version' => 'App Version',

    'copyright_title' => 'Copyright',
    'copyright_content' => 'Copyright &COPY; %1$s rGunti',

    'language' => 'Language',
    'languages' => 'Languages',

    'login' => 'Login',
    'logout' => 'Logout',
    'save' => 'Save',

    'debug_title' => 'Debug Info',
    'debug_no_items' => 'no items',
    'debug_session_info' => 'Session Info',
    'debug_instance' => 'Instance',

    'home' => 'Home',

    'username' => 'Username',
    'password' => 'Password',
    'mail_address' => 'Mail address',

    'toggle_nav' => 'Toggle navigation',

    'user_settings_title' => 'User Settings',
    'change_password' => 'Change Password',
    'confirm_password' => 'Confirm new Password',
    'change_password_help' => 'If you don\'t want to change your password, leave the password fields empty.',

    'tos_title' => 'Terms Of Use',
    'tos_content' => 'Terms of use have not been defined yet.',

    'message_logged_in' => 'Welcome, %1$s',
    'message_logged_in_content' => 'Your login was successful!',
    'message_logged_out' => 'You have been logged out!',

    'error_login_invalid' => 'Invalid Login Credentials',
    'error_login_invalid_content' => 'Your Login Credentials seem to be invalid. Please check your entry and try again.',

    'error_login_blocked' => 'Blocked',
    'error_login_blocked_content' => 'Your account has been blocked.',

    'error_navigation_login_needed' => 'Login needed',
    'error_navigation_login_needed_content' => 'Please login in order to access this content.',

    'error_navigation_admin_needed' => 'Administrative Permission required',
    'error_navigation_admin_needed_content' => 'You cannot access this content because you do not have the required administrative permission.',

    'admin_tools' => 'Admin Tools',
    'admin_tools_users' => 'Manage Users',

    'id' => 'ID',
    'admin_permission' => 'Administrative Permissions',
    'admin_permission_short' => 'Admin',
    'batch' => 'Batch User',
    'batch_short' => 'Batch',
    'disabled' => 'User Disabled',
    'disabled_short' => 'Disabled',
    'actions' => 'Actions',

    'disable_login' => 'Lock account',
    'enable_login' => 'Unlock account',
    'reset_password' => 'Reset password',
    'delete_user' => 'Delete account',

    'datatable_decimal' => '.',
    'datatable_thousands' => ',',
    'datatable_empty' => 'No data available',
    'datatable_info' => 'Showing _START_ to _END_ of _TOTAL_ entries',
    'datatable_info_empty' => 'No entries available',
    'datatable_info_filtered' => '(filtered from _MAX_ total entries)',
    'datatable_info_postfix' => '',
    'datatable_length_menu' => 'Show _MENU_ entries',
    'datatable_loading' => 'Loading...',
    'datatable_processing' => 'Processing...',
    'datatable_search' => 'Quick Search: ',
    'datatable_zero_records' => 'No matching records found',
    'datatable_paginate_first' => 'First',
    'datatable_paginate_last' => 'Last',
    'datatable_paginate_next' => 'Next',
    'datatable_paginate_prev' => 'Prev.',
    'datatable_aria_sort_asc' => ': activate to sort column ascending',
    'datatable_aria_sort_desc' => ': activate to sort column descending',
];
