<?php
return [
    '_LANG_NAME' => 'English (default)',
    '_LANG_AUTHOR' => 'rGunti',
    '_LANG_BY_STRING' => 'by %1$s',

    'app_version' => 'App Version',

    'copyright_title' => 'Copyright',
    'copyright_content' => 'Copyright &COPY; %1$s rGunti',

    'language' => 'Language',
    'languages' => 'Languages',

    'login' => 'Login',
    'logout' => 'Logout',

    'debug_title' => 'Debug Info',
    'debug_no_items' => 'no items',
    'debug_session_info' => 'Session Info',
    'debug_instance' => 'Instance',

    'home' => 'Home',

    'username' => 'Username',
    'password' => 'Password',

    'toggle_nav' => 'Toggle navigation',

    'user_settings_title' => 'User Settings',

    'tos_title' => 'Terms Of Use',
    'tos_content' => 'Terms of use have not been defined yet.',
];
