<?php echo json_encode([
    "decimal" => t('datatable_decimal'),
    "thousands" => t('datatable_thousands'),

    "emptyTable" => t('datatable_empty'),
    "info" => t('datatable_info'),
    "infoEmpty" => t('datatable_info_empty'),
    "infoFiltered" => t('datatable_info_filtered'),
    "infoPostFix" => t('datatable_info_postfix'),
    "lengthMenu" => t('datatable_length_menu'),
    "loadingRecords" => t('datatable_loading'),
    "processing" => t('datatable_processing'),
    "search" => t('datatable_search'),
    "zeroRecords" => t('datatable_zero_records'),
    "paginate" => [
        "first" => t('datatable_paginate_first'),
        "last" => t('datatable_paginate_last'),
        "next" => t('datatable_paginate_next'),
        "previous" => t('datatable_paginate_prev')
    ],
    "aria" => [
        "sortAscending" => t('datatable_aria_sort_asc'),
        "sortDescending" => t('datatable_aria_sort_desc')
    ]
]);
